# Generated by Django 5.2.16 on 2026-07-19 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_register', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100)),
                ('pelunasan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_lunas', models.CharField(choices=[('Belum', 'Belum'), ('Lunas', 'Lunas')], default='Belum', max_length=10)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to='master.stakeholder')),
                ('perkiraan_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances_cash', to='master.chartofaccount')),
                ('perkiraan_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances_loan', to='master.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCashAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_register', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_advance_payments', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('kas_bon_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.employeecashadvance')),
                ('perkiraan_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_advance_payments', to='master.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_bukti', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('km_terakhir', models.PositiveIntegerField(default=0)),
                ('km_sekarang', models.PositiveIntegerField(default=0)),
                ('nominal_bbm', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('armada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_purchases', to='master.armada')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_purchases', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_purchases_as_driver', to='master.stakeholder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_bukti', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('debet', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('biaya_adm_bank', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('uraian', models.TextField(blank=True)),
                ('akun_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions_target', to='master.chartofaccount')),
                ('akun_utama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions_primary', to='master.chartofaccount')),
                ('bank_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions_target', to='master.bankaccount')),
                ('bank_utama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions_primary', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('jenis_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='master.transactiontype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'no_bukti'), name='uniq_banktransaction_tenant_no_bukti')],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_bukti', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal_masuk', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nominal_keluar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('akun_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_account_transactions', to='master.chartofaccount')),
                ('akun_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_offset_transactions', to='master.chartofaccount')),
                ('armada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='master.armada')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'no_bukti'), name='uniq_cashtransaction_tenant_no_bukti')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeecashadvance',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_register'), name='uniq_cashadvance_tenant_no_register'),
        ),
        migrations.AddConstraint(
            model_name='employeecashadvancepayment',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_register'), name='uniq_cashadvancepayment_tenant_no_register'),
        ),
        migrations.AddConstraint(
            model_name='fuelpurchase',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_bukti'), name='uniq_fuelpurchase_tenant_no_bukti'),
        ),
    ]
