# Generated by Django 5.2.16 on 2026-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='no_bukti',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='no_bukti',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeecashadvance',
            name='no_register',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeecashadvancepayment',
            name='no_register',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelpurchase',
            name='no_bukti',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
