# Generated by Django 5.2.16 on 2026-08-26 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_loandebt_loandebtpayment_and_more'),
        ('master', '0007_stakeholder_kode_pos_stakeholder_lokasi_kerja_and_more'),
        ('tenants', '0003_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_register', models.CharField(blank=True, max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100)),
                ('pelunasan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_lunas', models.CharField(choices=[('Belum', 'Belum'), ('Lunas', 'Lunas')], default='Belum', max_length=10)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivables', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('penerima_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivables', to='master.stakeholder')),
                ('perkiraan_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivables_cash', to='master.chartofaccount')),
                ('perkiraan_piutang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivables_account', to='master.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_register', models.CharField(blank=True, max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.TextField(blank=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivable_payments', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('perkiraan_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_receivable_payments', to='master.chartofaccount')),
                ('piutang_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.loanreceivable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='loanreceivable',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_register'), name='uniq_loanreceivable_tenant_no_register'),
        ),
        migrations.AddConstraint(
            model_name='loanreceivablepayment',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_register'), name='uniq_loanreceivablepayment_tenant_no_register'),
        ),
    ]
