# Generated by Django 5.2.16 on 2026-07-25 06:28

import django.core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, help_text='Gunakan logo square PNG/JPEG. Rekomendasi 512 x 512 px atau 1024 x 1024 px.', upload_to='tenant_logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), tenants.models.validate_square_logo]),
        ),
    ]
