# Generated by Django 5.2.16 on 2026-07-23 02:31

from django.db import migrations, models


def populate_account_levels(apps, schema_editor):
    ChartOfAccount = apps.get_model('master', 'ChartOfAccount')

    def set_level(account, level):
        ChartOfAccount.objects.filter(pk=account.pk).update(level=level)
        for child in ChartOfAccount.objects.filter(parent_id=account.pk, is_deleted=False):
            set_level(child, level + 1)

    roots = ChartOfAccount.objects.filter(parent__isnull=True, is_deleted=False)
    for account in roots:
        set_level(account, 0)




class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_armada_uuid_bankaccount_uuid_chartofaccount_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='golongan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='kelompok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(populate_account_levels, migrations.RunPython.noop),
    ]
