# Generated by Django 5.2.16 on 2026-07-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_chartofaccount_golongan_chartofaccount_kelompok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
