# Generated by Django 5.2.16 on 2026-07-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_transactiontype_akun_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='lokasi_kerja',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='no_ktp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='jenis',
            field=models.CharField(choices=[('customer', 'Customer'), ('karyawan', 'Karyawan')], max_length=20),
        ),
    ]
