# Generated by Django 5.2.16 on 2026-07-19 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_invoice', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('pekerjaan', models.TextField(blank=True)),
                ('nilai_pekerjaan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ppn_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ppn', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('terbilang', models.TextField(blank=True)),
                ('pelunasan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_lunas', models.CharField(choices=[('Belum', 'Belum'), ('Lunas', 'Lunas')], default='Belum', max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='master.stakeholder')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('perkiraan_piutang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='master.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_register', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('nominal_kas', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pph', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pph_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('keterangan', models.TextField(blank=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100)),
                ('terbilang', models.TextField(blank=True)),
                ('ppn', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='master.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('perkiraan_kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments_cash', to='master.chartofaccount')),
                ('perkiraan_pph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments_pph', to='master.chartofaccount')),
                ('tagihan_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoice.customerinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_invoice'), name='uniq_customerinvoice_tenant_no_invoice'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoicepayment',
            constraint=models.UniqueConstraint(fields=('tenant', 'no_register'), name='uniq_invoicepayment_tenant_no_register'),
        ),
    ]
