# Generated by Django 5.2.16 on 2026-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='no_jurnal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
